### ISSUE TITLE
#11 based 스크린샷 범위 5: 우편, 인벤토리, 인연, 공지 및 이벤트, 이벤트 패키지 Flowchart

### ISSUE THREAD

**Issue by riohoekman** [sem1308/group1#23]

**Comment by tank3a** [comment]
[우편 순서도 추가](https://github.com/sem1308/group1/blob/master/181102flowchart/img_kimjw/%EC%9A%B0%ED%8E%B8%20%EC%88%9C%EC%84%9C%EB%8F%84.png)

**Comment by tank3a** [comment]
[인벤토리 순서도 추가](https://github.com/sem1308/group1/blob/master/181102flowchart/img_kimjw/%EC%9D%B8%EB%B2%A4%ED%86%A0%EB%A6%AC%20%EC%88%9C%EC%84%9C%EB%8F%84.png)

**Comment by tank3a** [comment]
[인연 순서도 추가](https://github.com/sem1308/group1/blob/master/181102flowchart/img_kimjw/%EC%9D%B8%EC%97%B0%20%EC%88%9C%EC%84%9C%EB%8F%84.png)
